import assert from 'node:assert/strict'
import test from 'node:test'
import shellExtension from './restrict-bash.ts'

type ToolCallHandler = (event: unknown, ctx?: unknown) => unknown | Promise<unknown>

test('blocks forbidden built-in tools and allows ls', async () => {
  const handler = createToolCallHandler()
  const grepResult = await handler({ toolName: 'grep', input: { pattern: 'x', path: '.' } })
  assert(isBlocked(grepResult))
  assert.match(grepResult.reason, /The `grep` tool is blocked/)
  const lsResult = await handler({ toolName: 'ls', input: { path: '.' } })
  assert.equal(lsResult, undefined)
})

test('blocks bash tool calls without a command', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: {} })
  assert(isBlocked(result))
  assert.match(result.reason, /called without a command/)
})

test('blocks command substitution and variable expansion', async () => {
  const handler = createToolCallHandler()
  const backticks = await handler({ toolName: 'bash', input: { command: 'echo `date`' } })
  assert(isBlocked(backticks))
  assert.match(backticks.reason, /backticks/)
  const dollarParens = await handler({ toolName: 'bash', input: { command: 'echo $(date)' } })
  assert(isBlocked(dollarParens))
  assert.match(dollarParens.reason, /\$\(\)/)
  const variableExpansion = await handler({ toolName: 'bash', input: { command: 'echo $HOME' } })
  assert(isBlocked(variableExpansion))
  assert.match(variableExpansion.reason, /Variable expansion/)
})

test('allows pipes and redirections while blocking subshell syntax and background execution', async () => {
  const handler = createToolCallHandler()
  const outputRedirect = await handler({ toolName: 'bash', input: { command: 'echo hi > out.txt' } })
  assert.equal(outputRedirect, undefined)
  const inputRedirect = await handler({ toolName: 'bash', input: { command: 'wc -l < input.txt' } })
  assert.equal(inputRedirect, undefined)
  const stdoutRedirect = await handler({ toolName: 'bash', input: { command: 'echo hi 2>&1' } })
  assert.equal(stdoutRedirect, undefined)
  const stderrRedirect = await handler({ toolName: 'bash', input: { command: 'echo hi 1>&2' } })
  assert.equal(stderrRedirect, undefined)
  const pipe = await handler({ toolName: 'bash', input: { command: 'echo hi | wc -c' } })
  assert.equal(pipe, undefined)
  const subshell = await handler({ toolName: 'bash', input: { command: '(echo hi)' } })
  assert(isBlocked(subshell))
  assert.match(subshell.reason, /Subshell/)
  const background = await handler({ toolName: 'bash', input: { command: 'sleep 1 &' } })
  assert(isBlocked(background))
  assert.match(background.reason, /Background execution/)
})

test('blocks unterminated quotes', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: 'echo "hi' } })
  assert(isBlocked(result))
  assert.match(result.reason, /Unterminated quotes/)
})

test('blocks restricted wrappers and allows time and ls', async () => {
  const handler = createToolCallHandler()
  const wrapper = await handler({ toolName: 'bash', input: { command: 'eval echo hi' } })
  assert(isBlocked(wrapper))
  assert.match(wrapper.reason, /wrapper command is blocked/)
  const timeWrapper = await handler({ toolName: 'bash', input: { command: 'time npx cowsay hi' } })
  assert.equal(timeWrapper, undefined)
  const watchWrapper = await handler({ toolName: 'bash', input: { command: 'watch -n 1 npx cowsay hi' } })
  assert(isBlocked(watchWrapper))
  assert.match(watchWrapper.reason, /wrapper command is blocked/)
  const stdbufWrapper = await handler({ toolName: 'bash', input: { command: 'stdbuf -oL npx cowsay hi' } })
  assert(isBlocked(stdbufWrapper))
  assert.match(stdbufWrapper.reason, /wrapper command is blocked/)
  const listing = await handler({ toolName: 'bash', input: { command: 'command ls -la' } })
  assert.equal(listing, undefined)
  const timeoutWrapper = await handler({ toolName: 'bash', input: { command: 'timeout 10 npm test' } })
  assert.equal(timeoutWrapper, undefined)
})

test('allows command runners and scaffolding launchers', async () => {
  const handler = createToolCallHandler()
  const npxResult = await handler({ toolName: 'bash', input: { command: 'npx cowsay hi' } })
  assert.equal(npxResult, undefined)
  const uvxResult = await handler({ toolName: 'bash', input: { command: 'uvx ruff check .' } })
  assert.equal(uvxResult, undefined)
  const bunxResult = await handler({ toolName: 'bash', input: { command: 'bunx cowsay hi' } })
  assert.equal(bunxResult, undefined)
  const pnpxResult = await handler({ toolName: 'bash', input: { command: 'pnpx cowsay hi' } })
  assert.equal(pnpxResult, undefined)
  const pnpmDlxResult = await handler({ toolName: 'bash', input: { command: 'pnpm dlx cowsay hi' } })
  assert.equal(pnpmDlxResult, undefined)
  const pnpmDlxWithFlagResult = await handler({ toolName: 'bash', input: { command: 'pnpm --filter foo dlx cowsay hi' } })
  assert.equal(pnpmDlxWithFlagResult, undefined)
  const yarnDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn dlx cowsay hi' } })
  assert.equal(yarnDlxResult, undefined)
  const yarnDlxWithFlagResult = await handler({ toolName: 'bash', input: { command: 'yarn --cwd . dlx cowsay hi' } })
  assert.equal(yarnDlxWithFlagResult, undefined)
  const yarnWorkspaceDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn workspace my-app dlx cowsay hi' } })
  assert.equal(yarnWorkspaceDlxResult, undefined)
  const yarnWorkspacesForeachDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn workspaces foreach dlx cowsay hi' } })
  assert.equal(yarnWorkspacesForeachDlxResult, undefined)
  const npmExecResult = await handler({ toolName: 'bash', input: { command: 'npm exec cowsay hi' } })
  assert.equal(npmExecResult, undefined)
  const npmExecWithFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --prefix . exec cowsay hi' } })
  assert.equal(npmExecWithFlagResult, undefined)
  const npmExecWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --cache /tmp exec cowsay hi' } })
  assert.equal(npmExecWithUnknownValueFlagResult, undefined)
  const npmWorkspaceExecResult = await handler({ toolName: 'bash', input: { command: 'npm workspace my-app exec cowsay hi' } })
  assert.equal(npmWorkspaceExecResult, undefined)
  const npmWorkspacesExecResult = await handler({ toolName: 'bash', input: { command: 'npm workspaces exec cowsay hi' } })
  assert.equal(npmWorkspacesExecResult, undefined)
  const bunXResult = await handler({ toolName: 'bash', input: { command: 'bun x cowsay hi' } })
  assert.equal(bunXResult, undefined)
  const uvToolRunResult = await handler({ toolName: 'bash', input: { command: 'uv tool run ruff check .' } })
  assert.equal(uvToolRunResult, undefined)
  const uvToolRunWithInterleavedFlagResult = await handler({ toolName: 'bash', input: { command: 'uv tool --verbose run ruff check .' } })
  assert.equal(uvToolRunWithInterleavedFlagResult, undefined)
  const uvToolRunWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'uv --index-url https://example.com tool run ruff check .' } })
  assert.equal(uvToolRunWithUnknownValueFlagResult, undefined)
  const npmCreateResult = await handler({ toolName: 'bash', input: { command: 'npm create vite@latest app' } })
  assert.equal(npmCreateResult, undefined)
  const npmCreateWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --registry https://evil.com create vite@latest app' } })
  assert.equal(npmCreateWithUnknownValueFlagResult, undefined)
  const npmCreateWithUserConfigFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --userconfig ./my-conf create vite app' } })
  assert.equal(npmCreateWithUserConfigFlagResult, undefined)
  const npmInitResult = await handler({ toolName: 'bash', input: { command: 'npm init vite@latest app' } })
  assert.equal(npmInitResult, undefined)
  const yarnCreateResult = await handler({ toolName: 'bash', input: { command: 'yarn create vite app' } })
  assert.equal(yarnCreateResult, undefined)
  const pnpmCreateResult = await handler({ toolName: 'bash', input: { command: 'pnpm create vite app' } })
  assert.equal(pnpmCreateResult, undefined)
  const bunCreateResult = await handler({ toolName: 'bash', input: { command: 'bun create vite app' } })
  assert.equal(bunCreateResult, undefined)
  const npmCreateAfterDashDashResult = await handler({ toolName: 'bash', input: { command: 'npm help -- create' } })
  assert.equal(npmCreateAfterDashDashResult, undefined)
  const pnpmExecResult = await handler({ toolName: 'bash', input: { command: 'pnpm exec cowsay hi' } })
  assert.equal(pnpmExecResult, undefined)
  const npmInstallExecPackageResult = await handler({ toolName: 'bash', input: { command: 'npm install exec' } })
  assert.equal(npmInstallExecPackageResult, undefined)
  const npmRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm run create' } })
  assert.equal(npmRunCreateScriptResult, undefined)
  const npmSilentRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm --silent run create' } })
  assert.equal(npmSilentRunCreateScriptResult, undefined)
  const npmCacheEqualsRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm --cache=/tmp run create' } })
  assert.equal(npmCacheEqualsRunCreateScriptResult, undefined)
  const yarnSilentRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'yarn --silent run create' } })
  assert.equal(yarnSilentRunCreateScriptResult, undefined)
  const yarnCwdEqualsRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'yarn --cwd=. run create' } })
  assert.equal(yarnCwdEqualsRunCreateScriptResult, undefined)
  const npmSilentCreateResult = await handler({ toolName: 'bash', input: { command: 'npm --silent create vite@latest app' } })
  assert.equal(npmSilentCreateResult, undefined)
  const yarnAddDlxPackageResult = await handler({ toolName: 'bash', input: { command: 'yarn add dlx' } })
  assert.equal(yarnAddDlxPackageResult, undefined)
})

test('allows run-script commands across package managers', async () => {
  const handler = createToolCallHandler()
  const npmRunBuildResult = await handler({ toolName: 'bash', input: { command: 'npm run build' } })
  assert.equal(npmRunBuildResult, undefined)
  const npmRunTestResult = await handler({ toolName: 'bash', input: { command: 'npm run test' } })
  assert.equal(npmRunTestResult, undefined)
  const yarnRunBuildResult = await handler({ toolName: 'bash', input: { command: 'yarn run build' } })
  assert.equal(yarnRunBuildResult, undefined)
  const yarnRunCreateResult = await handler({ toolName: 'bash', input: { command: 'yarn run create' } })
  assert.equal(yarnRunCreateResult, undefined)
  const yarnWorkspacesForeachRunBuildResult = await handler({ toolName: 'bash', input: { command: 'yarn workspaces foreach run build' } })
  assert.equal(yarnWorkspacesForeachRunBuildResult, undefined)
  const pnpmRunBuildResult = await handler({ toolName: 'bash', input: { command: 'pnpm run build' } })
  assert.equal(pnpmRunBuildResult, undefined)
  const pnpmRunCreateResult = await handler({ toolName: 'bash', input: { command: 'pnpm run create' } })
  assert.equal(pnpmRunCreateResult, undefined)
  const bunRunBuildResult = await handler({ toolName: 'bash', input: { command: 'bun run build' } })
  assert.equal(bunRunBuildResult, undefined)
  const bunRunCreateResult = await handler({ toolName: 'bash', input: { command: 'bun run create' } })
  assert.equal(bunRunCreateResult, undefined)
})

test('allows path-qualified launchers and ls', async () => {
  const handler = createToolCallHandler()
  const absoluteNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/local/bin/npx cowsay hi' } })
  assert.equal(absoluteNpxResult, undefined)
  const pathQualifiedEnvNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/bin/env npx cowsay hi' } })
  assert.equal(pathQualifiedEnvNpxResult, undefined)
  const pathQualifiedEnvWithFlagNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/bin/env -i npx cowsay hi' } })
  assert.equal(pathQualifiedEnvWithFlagNpxResult, undefined)
  const pathQualifiedCommandLsResult = await handler({ toolName: 'bash', input: { command: '/bin/command ls -la' } })
  assert.equal(pathQualifiedCommandLsResult, undefined)
  const relativeNpmCreateResult = await handler({ toolName: 'bash', input: { command: './node_modules/.bin/npm create vite@latest app' } })
  assert.equal(relativeNpmCreateResult, undefined)
  const absoluteLsResult = await handler({ toolName: 'bash', input: { command: '/bin/ls -la' } })
  assert.equal(absoluteLsResult, undefined)
})

test('blocks sed in-place edits', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: "sed -i 's/a/b/' file.txt" } })
  assert(isBlocked(result))
  assert.match(result.reason, /sed -i/)
})

test('allows all git commands', async () => {
  const handler = createToolCallHandler()
  const status = await handler({ toolName: 'bash', input: { command: 'git status' } })
  assert.equal(status, undefined)
  const commit = await handler({ toolName: 'bash', input: { command: 'git commit -m msg' } })
  assert.equal(commit, undefined)
  const commitWithGlobalFlag = await handler({ toolName: 'bash', input: { command: 'git -c foo=bar commit -m msg' } })
  assert.equal(commitWithGlobalFlag, undefined)
  const statusWithCwdFlag = await handler({ toolName: 'bash', input: { command: 'git -C repo status' } })
  assert.equal(statusWithCwdFlag, undefined)
})

test('blocks shell control-flow keywords', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: 'if true; then echo ok; fi' } })
  assert(isBlocked(result))
  assert.match(result.reason, /control-flow keyword/)
})

function createToolCallHandler(): ToolCallHandler {
  let toolCallHandler: ToolCallHandler | undefined
  const pi = {
    on: (eventName: string, handler: ToolCallHandler) => {
      if (eventName !== 'tool_call') return
      toolCallHandler = handler
    },
  }
  shellExtension(pi as never)
  assert(toolCallHandler)
  return toolCallHandler
}

function isBlocked(value: unknown): value is { block: true; reason: string } {
  if (!value || typeof value !== 'object') return false
  const candidate = value as { block?: unknown; reason?: unknown }
  return candidate.block === true && typeof candidate.reason === 'string'
}
